### ISSUE TITLE
'\xa0' 

### ISSUE THREAD

**Issue by meeffe** [masaccio/numbers-parser#24]
Hello again mate, 
When reading .numbers file I have to use some additional code to remove / replace '\xa0' from strings in pandas columns. This occurs all the time when there is a space (' ') OR ('-') and string look like this: 'python\xa0is\xa0cool'

There is no need to add these when I use standard read from excel in pandas. 

Any solution to make it work from the start without these additional strings replacing?

**Comment by masaccio** [comment]
Not sure what the root cause of that is but if you can attach a Numbers file (you'll need to zip) it then I could take a look. There are some workarounds though:https://stackoverflow.com/questions/55442727/remove-unicode-xa0-from-pandas-columnSeems a bit odd that the data as Unicode spaces rather than normal ones but not spotted that before.JonOn 26 Apr 2022, at 11:17, meeffe ***@***.***> wrote:Hello again mate, When reading .numbers file I have to use some additional code to remove / replace '\xa0' from strings in pandas columns. The occurs all the time when there is a space (' ') OR ('-') and string look like this: 'python\xa0is\xa0cool'There is no need to add these when I use standard read from excel in pandas.Any solution to make it work from the start without these additional strings replacing?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by masaccio** [comment]
It's not pandas as the data has It coming from numbers:

```
(Pdb) p tables[0].cell(1,0).value
'virgin\xa0mobile'
```

`\xa0` is a non-breaking space in Unicode which must be what's stored in the document. You can convert to ASCII like this:

``` python
import unicodedata
unicodedata.normalize("NFKD", tables[0].cell(1,0).value)
```

Pandas has a function for this: https://pandas.pydata.org/docs/reference/api/pandas.Series.str.normalize.html

In your example that would be:

``` python
df.product = df.produkt.str.normalize("NFKD")
```

**Comment by meeffe** [comment]
thanks
